name: Deploy Website to Apache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Website
        run: |
          # Add your build commands here
        env:
          NODE_ENV: production

      - name: Deploy to Apache
        run: |
          # Copy your built website to Apache's web root directory
          sudo cp -r ci-cd_test/* /var/www/html/

          # Restart Apache to apply changes
          sudo systemctl restart apache2
        env:
          APACHE_ENV: production
